#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TARGET_CYCLE_TIME_MICROSECONDS 5000
#define ENCODER_CLK_PIN 17
#define ENCODER_DT_PIN 18
#define ENCODER_PPR 1024
#define ENCODER_START_ANGLE_DEGREES 0
#define DELAY_FEEDBACK_GAIN 1.2
#define BYPASS_ROBOT 1

#endif