# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/inverted-pendulum-control

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/inverted-pendulum-control

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/inverted-pendulum-control/CMakeFiles /home/pi/inverted-pendulum-control//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/inverted-pendulum-control/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stabilizer

# Build rule for target.
stabilizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stabilizer
.PHONY : stabilizer

# fast build rule for target.
stabilizer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/build
.PHONY : stabilizer/fast

#=============================================================================
# Target rules for targets named robot-test

# Build rule for target.
robot-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 robot-test
.PHONY : robot-test

# fast build rule for target.
robot-test/fast:
	$(MAKE) $(MAKESILENT) -f meca500_ethercat_cpp/CMakeFiles/robot-test.dir/build.make meca500_ethercat_cpp/CMakeFiles/robot-test.dir/build
.PHONY : robot-test/fast

#=============================================================================
# Target rules for targets named meca500_driver

# Build rule for target.
meca500_driver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 meca500_driver
.PHONY : meca500_driver

# fast build rule for target.
meca500_driver/fast:
	$(MAKE) $(MAKESILENT) -f meca500_ethercat_cpp/CMakeFiles/meca500_driver.dir/build.make meca500_ethercat_cpp/CMakeFiles/meca500_driver.dir/build
.PHONY : meca500_driver/fast

#=============================================================================
# Target rules for targets named sun_ethercat_master

# Build rule for target.
sun_ethercat_master: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sun_ethercat_master
.PHONY : sun_ethercat_master

# fast build rule for target.
sun_ethercat_master/fast:
	$(MAKE) $(MAKESILENT) -f meca500_ethercat_cpp/sun_etherCAT/sun_ethercat_master/CMakeFiles/sun_ethercat_master.dir/build.make meca500_ethercat_cpp/sun_etherCAT/sun_ethercat_master/CMakeFiles/sun_ethercat_master.dir/build
.PHONY : sun_ethercat_master/fast

#=============================================================================
# Target rules for targets named soem

# Build rule for target.
soem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soem
.PHONY : soem

# fast build rule for target.
soem/fast:
	$(MAKE) $(MAKESILENT) -f meca500_ethercat_cpp/sun_etherCAT/SOEM/CMakeFiles/soem.dir/build.make meca500_ethercat_cpp/sun_etherCAT/SOEM/CMakeFiles/soem.dir/build
.PHONY : soem/fast

#=============================================================================
# Target rules for targets named sun_scheduling

# Build rule for target.
sun_scheduling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sun_scheduling
.PHONY : sun_scheduling

# fast build rule for target.
sun_scheduling/fast:
	$(MAKE) $(MAKESILENT) -f meca500_ethercat_cpp/sun_etherCAT/sun_scheduling/CMakeFiles/sun_scheduling.dir/build.make meca500_ethercat_cpp/sun_etherCAT/sun_scheduling/CMakeFiles/sun_scheduling.dir/build
.PHONY : sun_scheduling/fast

#=============================================================================
# Target rules for targets named sun_slave

# Build rule for target.
sun_slave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sun_slave
.PHONY : sun_slave

# fast build rule for target.
sun_slave/fast:
	$(MAKE) $(MAKESILENT) -f meca500_ethercat_cpp/sun_etherCAT/sun_slave/CMakeFiles/sun_slave.dir/build.make meca500_ethercat_cpp/sun_etherCAT/sun_slave/CMakeFiles/sun_slave.dir/build
.PHONY : sun_slave/fast

#=============================================================================
# Target rules for targets named sun_controller

# Build rule for target.
sun_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sun_controller
.PHONY : sun_controller

# fast build rule for target.
sun_controller/fast:
	$(MAKE) $(MAKESILENT) -f meca500_ethercat_cpp/sun_etherCAT/sun_controller/CMakeFiles/sun_controller.dir/build.make meca500_ethercat_cpp/sun_etherCAT/sun_controller/CMakeFiles/sun_controller.dir/build
.PHONY : sun_controller/fast

Constants.o: Constants.cpp.o

.PHONY : Constants.o

# target to build an object file
Constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/Constants.cpp.o
.PHONY : Constants.cpp.o

Constants.i: Constants.cpp.i

.PHONY : Constants.i

# target to preprocess a source file
Constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/Constants.cpp.i
.PHONY : Constants.cpp.i

Constants.s: Constants.cpp.s

.PHONY : Constants.s

# target to generate assembly for a file
Constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/Constants.cpp.s
.PHONY : Constants.cpp.s

src/controller/FeedbackController.o: src/controller/FeedbackController.cpp.o

.PHONY : src/controller/FeedbackController.o

# target to build an object file
src/controller/FeedbackController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/controller/FeedbackController.cpp.o
.PHONY : src/controller/FeedbackController.cpp.o

src/controller/FeedbackController.i: src/controller/FeedbackController.cpp.i

.PHONY : src/controller/FeedbackController.i

# target to preprocess a source file
src/controller/FeedbackController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/controller/FeedbackController.cpp.i
.PHONY : src/controller/FeedbackController.cpp.i

src/controller/FeedbackController.s: src/controller/FeedbackController.cpp.s

.PHONY : src/controller/FeedbackController.s

# target to generate assembly for a file
src/controller/FeedbackController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/controller/FeedbackController.cpp.s
.PHONY : src/controller/FeedbackController.cpp.s

src/csvlogger/CsvLogger.o: src/csvlogger/CsvLogger.cpp.o

.PHONY : src/csvlogger/CsvLogger.o

# target to build an object file
src/csvlogger/CsvLogger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/csvlogger/CsvLogger.cpp.o
.PHONY : src/csvlogger/CsvLogger.cpp.o

src/csvlogger/CsvLogger.i: src/csvlogger/CsvLogger.cpp.i

.PHONY : src/csvlogger/CsvLogger.i

# target to preprocess a source file
src/csvlogger/CsvLogger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/csvlogger/CsvLogger.cpp.i
.PHONY : src/csvlogger/CsvLogger.cpp.i

src/csvlogger/CsvLogger.s: src/csvlogger/CsvLogger.cpp.s

.PHONY : src/csvlogger/CsvLogger.s

# target to generate assembly for a file
src/csvlogger/CsvLogger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/csvlogger/CsvLogger.cpp.s
.PHONY : src/csvlogger/CsvLogger.cpp.s

src/encoder/Encoder.o: src/encoder/Encoder.cpp.o

.PHONY : src/encoder/Encoder.o

# target to build an object file
src/encoder/Encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/encoder/Encoder.cpp.o
.PHONY : src/encoder/Encoder.cpp.o

src/encoder/Encoder.i: src/encoder/Encoder.cpp.i

.PHONY : src/encoder/Encoder.i

# target to preprocess a source file
src/encoder/Encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/encoder/Encoder.cpp.i
.PHONY : src/encoder/Encoder.cpp.i

src/encoder/Encoder.s: src/encoder/Encoder.cpp.s

.PHONY : src/encoder/Encoder.s

# target to generate assembly for a file
src/encoder/Encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/encoder/Encoder.cpp.s
.PHONY : src/encoder/Encoder.cpp.s

src/encoder/rotary_encoder/rotary_encoder.o: src/encoder/rotary_encoder/rotary_encoder.cpp.o

.PHONY : src/encoder/rotary_encoder/rotary_encoder.o

# target to build an object file
src/encoder/rotary_encoder/rotary_encoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/encoder/rotary_encoder/rotary_encoder.cpp.o
.PHONY : src/encoder/rotary_encoder/rotary_encoder.cpp.o

src/encoder/rotary_encoder/rotary_encoder.i: src/encoder/rotary_encoder/rotary_encoder.cpp.i

.PHONY : src/encoder/rotary_encoder/rotary_encoder.i

# target to preprocess a source file
src/encoder/rotary_encoder/rotary_encoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/encoder/rotary_encoder/rotary_encoder.cpp.i
.PHONY : src/encoder/rotary_encoder/rotary_encoder.cpp.i

src/encoder/rotary_encoder/rotary_encoder.s: src/encoder/rotary_encoder/rotary_encoder.cpp.s

.PHONY : src/encoder/rotary_encoder/rotary_encoder.s

# target to generate assembly for a file
src/encoder/rotary_encoder/rotary_encoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/encoder/rotary_encoder/rotary_encoder.cpp.s
.PHONY : src/encoder/rotary_encoder/rotary_encoder.cpp.s

src/timer/Timer.o: src/timer/Timer.cpp.o

.PHONY : src/timer/Timer.o

# target to build an object file
src/timer/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/timer/Timer.cpp.o
.PHONY : src/timer/Timer.cpp.o

src/timer/Timer.i: src/timer/Timer.cpp.i

.PHONY : src/timer/Timer.i

# target to preprocess a source file
src/timer/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/timer/Timer.cpp.i
.PHONY : src/timer/Timer.cpp.i

src/timer/Timer.s: src/timer/Timer.cpp.s

.PHONY : src/timer/Timer.s

# target to generate assembly for a file
src/timer/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/timer/Timer.cpp.s
.PHONY : src/timer/Timer.cpp.s

src/timer/timerStats/TimerStats.o: src/timer/timerStats/TimerStats.cpp.o

.PHONY : src/timer/timerStats/TimerStats.o

# target to build an object file
src/timer/timerStats/TimerStats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/timer/timerStats/TimerStats.cpp.o
.PHONY : src/timer/timerStats/TimerStats.cpp.o

src/timer/timerStats/TimerStats.i: src/timer/timerStats/TimerStats.cpp.i

.PHONY : src/timer/timerStats/TimerStats.i

# target to preprocess a source file
src/timer/timerStats/TimerStats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/timer/timerStats/TimerStats.cpp.i
.PHONY : src/timer/timerStats/TimerStats.cpp.i

src/timer/timerStats/TimerStats.s: src/timer/timerStats/TimerStats.cpp.s

.PHONY : src/timer/timerStats/TimerStats.s

# target to generate assembly for a file
src/timer/timerStats/TimerStats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/src/timer/timerStats/TimerStats.cpp.s
.PHONY : src/timer/timerStats/TimerStats.cpp.s

stabilizer.o: stabilizer.cpp.o

.PHONY : stabilizer.o

# target to build an object file
stabilizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/stabilizer.cpp.o
.PHONY : stabilizer.cpp.o

stabilizer.i: stabilizer.cpp.i

.PHONY : stabilizer.i

# target to preprocess a source file
stabilizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/stabilizer.cpp.i
.PHONY : stabilizer.cpp.i

stabilizer.s: stabilizer.cpp.s

.PHONY : stabilizer.s

# target to generate assembly for a file
stabilizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stabilizer.dir/build.make CMakeFiles/stabilizer.dir/stabilizer.cpp.s
.PHONY : stabilizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... meca500_driver"
	@echo "... robot-test"
	@echo "... soem"
	@echo "... stabilizer"
	@echo "... sun_controller"
	@echo "... sun_ethercat_master"
	@echo "... sun_scheduling"
	@echo "... sun_slave"
	@echo "... Constants.o"
	@echo "... Constants.i"
	@echo "... Constants.s"
	@echo "... src/controller/FeedbackController.o"
	@echo "... src/controller/FeedbackController.i"
	@echo "... src/controller/FeedbackController.s"
	@echo "... src/csvlogger/CsvLogger.o"
	@echo "... src/csvlogger/CsvLogger.i"
	@echo "... src/csvlogger/CsvLogger.s"
	@echo "... src/encoder/Encoder.o"
	@echo "... src/encoder/Encoder.i"
	@echo "... src/encoder/Encoder.s"
	@echo "... src/encoder/rotary_encoder/rotary_encoder.o"
	@echo "... src/encoder/rotary_encoder/rotary_encoder.i"
	@echo "... src/encoder/rotary_encoder/rotary_encoder.s"
	@echo "... src/timer/Timer.o"
	@echo "... src/timer/Timer.i"
	@echo "... src/timer/Timer.s"
	@echo "... src/timer/timerStats/TimerStats.o"
	@echo "... src/timer/timerStats/TimerStats.i"
	@echo "... src/timer/timerStats/TimerStats.s"
	@echo "... stabilizer.o"
	@echo "... stabilizer.i"
	@echo "... stabilizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

